version: '3'
services:
  user_api:
    build: ./user_api
    environment:
      ACTIVATION_DELAY: 60  # activation delay in seconds before a code expires
      TOKEN_DELAY: 300      # token delay validity
    depends_on:
      - db
      - fake_smtp_server
  
  fake_smtp_server:
    build: ./fake_smtp_server
    environment:
      FROM_EMAIL: noreply@exercise-dm.fake  # email of the sender

  db:
    image: docker pull postgres:14-alpine
    restart: always
    environment:
      TZ: "Europe/Paris"  # local timestamp of the machine
      POSTGRES_DB: users
      POSTGRES_PASSWORD: "change-me"
      #TODO: init DB (create tables)
